trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: ninhu/r-sdk-build:latest

variables:
  ${{ if in( variables['Build.Reason'], 'Manual', 'IndividualCI') }}:
    TEST_SUBSCRIPTION_ID: ${{ variables['CI_SUBSCRIPTION_ID'] }}

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        pip install --user azureml-sdk
        R -e 'dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE);
              .libPaths(Sys.getenv("R_LIBS_USER"));
              # build and install R sdk
              devtools::install_deps(upgrade = FALSE);
              package_location <- devtools::build();
              install.packages(package_location, repos = NULL)'
    displayName: 'Build and Install SDK'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        python -c "if ('$servicePrincipalId' and '$servicePrincipalKey' and '$tenantId'): from azureml._base_sdk_common.common import perform_interactive_login; perform_interactive_login(username='$servicePrincipalId', password='$servicePrincipalKey', service_principal=True, tenant='$tenantId')"
        R -e '# needed to load all non exported packages for testing
              devtools::load_all();
              options(testthat.output_file = "TEST-ALL.xml");
              testthat::test_dir("tests/testthat", reporter = "junit")'
    displayName: 'Run R SDK Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
      failTaskOnFailedTests: true
