trigger:
  batch: true
  branches:
    include:
    - master

# no PR builds
pr: none

pool:
  vmImage: 'ubuntu-16.04'

container: ninhu/r-sdk-build:latest

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        git config --global user.email "$(GITHUB_USER_EMAIL)"
        git config --global user.name "$(GITHUB_USER_NAME)"
        branch_name = ${$(Build.SourceBranch)/"refs/heads"}
        echo GIT CHECKOUT
        git checkout $branch_name
        echo GIT PULL
        git pull
        echo UPDATE DOCS
        R -e 'unlink("man", recursive=TRUE, force=TRUE);
              unlink("docs", recursive=TRUE, force=TRUE);
              roxygen2::roxygenise();
              pkgdown::build_site();'
        echo GIT ADD
        git add man/* docs/*
        echo GIT COMMIT
        git commit -m "Update R SDK Docs via $(Build.DefinitionName) $(Build.BuildNumber) [skip ci]"
        echo GIT PUSH
        git push https://$(GITHUB_AUTH_TOKEN)@github.com/Azure/azureml-sdk-for-r.git
    displayName: 'Update Docs'
