trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: ninhu/r-sdk-build:test

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        R -e 'roxygen2::roxygenise();
              pkgdown::build_site();'
        ECHO GIT ADD
        git add man/* docs/*
        ECHO GIT COMMIT
        git commit -m "Update docs automatically"
        ECHO GIT PUSH
        git push
        ECHO GIT STATUS
        git status
    displayName: 'Update Docs'
