trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: ninhu/r-sdk-build:test

steps:
  - checkout: self
    persistCredentials: true

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo UPDATE DOCS
        R -e 'unlink("man", recursive=TRUE, force=TRUE);
              unlink("docs", recursive=TRUE, force=TRUE);
              roxygen2::roxygenise();
              pkgdown::build_site();'
        echo GIT ADD
        git add man/* docs/*
        echo GIT COMMIT
        git commit -m "Update docs automatically"
        ECHO GIT PUSH
        git push origin
    displayName: 'Update Docs'
