trigger:
  batch: true
  branches:
    include:
    - master

# no PR builds
pr: none

pool:
  vmImage: 'ubuntu-16.04'

container: ninhu/r-sdk-build:test

steps:
  - checkout: self
    persistCredentials: true

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        git config --global user.email "ninhu@microsoft.com"
        git config --global user.name "ninghu"
        echo SOURCE BRANCH IS $BUILD_SOURCEBRANCH
        ECHO GIT CHECKOUT MASTER
        git checkout ninhu/docs_build
        echo UPDATE DOCS
        R -e 'unlink("man", recursive=TRUE, force=TRUE);
              unlink("docs", recursive=TRUE, force=TRUE);
              roxygen2::roxygenise();
              pkgdown::build_site();'
        echo GIT ADD
        git add man/* docs/*
        echo GIT COMMIT
        git commit -m "Update R SDK Docs [skip ci]"
        echo GIT PUSH
        git push https://$(GITHUB_AUTH_TOKEN)@github.com/Azure/azureml-sdk-for-r.git
    displayName: 'Update Docs'
