trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: ninhu/r-sdk-build:latest

variables:
 ${{ if in( variables['Build.Reason'], 'Manual', 'IndividualCI') }}:
  TEST_SUBSCRIPTION_ID: $(CI_SUBSCRIPTION_ID)

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        pip install --user azureml-sdk
        R -e 'dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE);
              .libPaths(Sys.getenv("R_LIBS_USER"));
              # build and install R sdk
              devtools::install_deps(upgrade = FALSE);
              package_location <- devtools::build();
              install.packages(package_location, repos = NULL)'
    displayName: 'Build and Install SDK'

  - task: AzureCLI@1
    inputs:
      azureSubscription: 'Project Vienna Build Tests (4faaaf21-663f-4391-96fd-47197c630979)'
      scriptLocation: inlineScript
      inlineScript: |
        Rscript './.azure-pipelines/scripts/validate_samples.R' 'R'
      addSpnToEnvironment: true
    displayName: 'Validate Samples'
