name: Mark inactive issues as stale after 1 month and closes them after 2 months

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed unless the label is removed or if no further activity occurs within 30 days.'
        stale-issue-label: 'stale: no-recent-activity'
        days-before-stale: 30 # waits for 30 days of inactivity to mark stale
        days-before-close: 30 # waits for 30 extra days of inactivity before closing
